name: 'mobile_games'
version: '1.0.0'
profile: 'mobile_games'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  mobile_games:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table